//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOLAZO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CANCHA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CANCHA()
        {
            this.HORA = new HashSet<HORA>();
        }
    
        public int ID { get; set; }
        public string DESCRIPCION { get; set; }
        public decimal VALOR_HORA { get; set; }
        public int DEPORTE { get; set; }
        public int PISO_CANCHA { get; set; }
        public int COMPLEJO { get; set; }
    
        public virtual COMPLEJO COMPLEJO1 { get; set; }
        public virtual DEPORTE DEPORTE1 { get; set; }
        public virtual PISO_CANCHA PISO_CANCHA1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HORA> HORA { get; set; }
    }
}
