//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOLAZO.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GolazoContext : DbContext
    {
        public GolazoContext()
            : base("name=GolazoContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CANCHA> CANCHA { get; set; }
        public virtual DbSet<COMPLEJO> COMPLEJO { get; set; }
        public virtual DbSet<DEPORTE> DEPORTE { get; set; }
        public virtual DbSet<HORA> HORA { get; set; }
        public virtual DbSet<LANDLORD> LANDLORD { get; set; }
        public virtual DbSet<PISO_CANCHA> PISO_CANCHA { get; set; }
        public virtual DbSet<RESERVA> RESERVA { get; set; }
        public virtual DbSet<TENANT> TENANT { get; set; }
    }
}
