//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOLAZO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVA
    {
        public int ID { get; set; }
        public System.DateTime FECHA { get; set; }
        public bool VIGENCIA { get; set; }
        public int HORA { get; set; }
        public int TENANT { get; set; }
    
        public virtual HORA HORA1 { get; set; }
        public virtual TENANT TENANT1 { get; set; }
    }
}
